export const stylesMui = {
  footerTitle: {
    // color: "var(--Main, #FFF)",
    textAlign: "center",
    fontFamily: "Montserrat",
    fontSize: { xs: "2rem", md: "2.75", lg: "3.375rem" },
    fontWeight: 600,
    lineHeight: "normal",
    textTransform: "capitalize",
  },
  footerSubtitle: {
    // color: "var(--Main, #FFF)",
    textAlign: "center",
    fontFamily: "Poppins",
    fontSize: { xs: "0.9rem", lg: "1.375rem" },
    fontWeight: 400,
    lineHeight: "normal",
    letterSpacing: "0.06875rem",
  },
  ctaButton: {
    py: { md: "0.25rem", xl: "0.85rem" },
    px: { md: "0.5rem", lg: "1.1rem", xl: "1.38rem" },
    borderRadius: "0 0.75rem 0.75rem 0",
    backgroundColor: "#00BE64 !important",
  },
  ctaButtonText: {
    // color: "var(--2, #FFF)",
    fontFamily: "Poppins",
    fontSize: "1rem",
    fontWeight: 600,
    lineHeight: "1.5rem",
    textTransform: "capitalize",
  },
  footerHeadings: {
    // color: "var(--white, #FFF)",
    fontSize: { xs: "1rem", lg: "1.5rem" },
    fontWeight: "500",
    lineHeight: "2rem",
  },
  contactText: {
    // color: "var(--Main, #FFF)",
    fontFamily: "Poppins",
    fontSize: "1.125rem",
    fontWeight: 400,
    lineHeight: "normal",
    textTransform: "capitalize",
  },
  copyrightText: {
    display: "flex",
    justifyContent: "center",
    textAlign: "center",
    // color: "var(--white, #FFF)",
    fontSize: { xs: "0.875rem", md: "1.125rem" },
    fontWeight: "500",
    lineHeight: "1rem",
    letterSpacing: "0.01rem",
  },
  emailInput: {
    // color: "var(--white, #FFF)",
    background: "rgba(255, 255, 255, 0.07)",
    // border: "1px rgba(255, 255, 255, 0.07) !important",
    borderRadius: "0.25rem",
    input: {
      "&::placeholder": {
        color: "white",
        opacity: 1,
      },
      color: "white",
    },
  },
  ctaTitle: {
    color: "var(--white, var(--White, #FFF))",
    fontFamily: "DM Sans",
    fontSize: "1.5rem",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "1.6245rem",
    letterSpacing: "0.05625rem",
    textTransform: "capitalize",
  },
  bodyText: {
    color: "#5E5E5E !important",
    textAlign: "start",
    fontFamily: "Montserrat",
    fontSize: "1.125rem",
    fontWeight: 500,
    lineHeight: "198.088%",
  },
  footerCtaButton: {
    borderRadius: "0.875rem",
    backgroundColor: "var(--Main, #00BE64) !important",
    display: "flex",
    height: "4.375rem",
    padding: "1.6875rem 2rem",
    justifyContent: "center",
    alignItems: "center",
    gap: "0.5rem",
  },
  footerCtaButtonText: {
    color: "var(--white, var(--White, #FFF))",
    textAlign: "center",
    fontFamily: "DM Sans",
    fontSize: "1rem",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "1rem",
    letterSpacing: "0.1rem",
    textTransform: "uppercase",
  },
};
