export const stylesMui = {
  featuredChallenge: {
    textAlign: "center",
    // color: "var(--2, #FFF)",
    fontFamily: "Montserrat",
    fontSize: { xs: "1.5rem", lg: "2rem", xl: "2.375rem" },
    fontWeight: 600,
    lineHeight: "normal",
  },
  cardBox: {
    width: "100%",
    padding: { xs: "0.75rem", sm: "1rem", lg: "1.5rem" },
    borderRadius: "0.75rem",
    border: "6px solid rgba(91, 28, 212, 0.50)",
    background: "rgba(255, 255, 255, 0.02)",
    boxShadow: "0px 0px 50px 0px rgba(91, 28, 212, 0.10)",
  },
  cardInactiveBox: {
    width: "100%",
    padding: { xs: "0.75rem", sm: "1rem", lg: "1.5rem" },
    borderRadius: "0.75rem",
    background: "rgba(255, 255, 255, 0.02)",
  },
  cardTitle: {
    // color: "var(--2, #FFF)",
    fontFamily: "Montserrat",
    fontSize: "1.75rem",
    fontWeight: 600,
    lineHeight: "normal",
  },
  cardText: {
    color: "var(--6, #646464)",
    fontFamily: "Poppins",
    fontSize: "1.125rem",
    fontWeight: 400,
    lineHeight: "normal",
    textTransform: "capitalize",
  },
  cardFooter: {
    color: "var(--6, #00BE64)",
    fontFamily: "Montserrat",
    fontSize: "0.875rem",
    fontWeight: 500,
    lineHeight: "normal",
  },
  cardButton: {
    backgroundColor: "#00BE64 !important",
    display: "flex",
    padding: {
      xs: "0.5rem 0.75rem",
      sm: "0.75rem 0.875rem",
      lg: "0.875rem 1rem",
    },
    justifyContent: "center",
    alignItems: "center",
    gap: "0.625rem",
  },
  cardButtonText: {
    // color: "var(--2, #FFF)",
    fontFamily: "Montserrat",
    fontSize: "1rem",
    fontWeight: 600,
    lineHeight: "normal",
  },
  challenges: {
    // color: "var(--2, #FFF)",
    fontFamily: "Montserrat",
    fontSize: { xs: "1.5rem", lg: "2rem", xl: "2.375rem" },
    fontWeight: 600,
    lineHeight: "normal",
  },
  challengesSubtext: {
    color: "var(--6, #00BE64)",
    fontFamily: "Montserrat",
    fontSize: "1.125rem",
    fontWeight: 400,
    lineHeight: "normal",
  },
  challengeWinner: {
    // color: "var(--2, #FFF)",
    fontFamily: "Montserrat",
    fontSize: "1.125rem",
    fontWeight: 600,
    lineHeight: "normal",
  },
};
